export * from "./HomeIcon";
export * from "./PersonIcon";
export * from "./WorkIcon";
export * from "./ContactIcon";
export * from "./FacebookIcon";
export * from "./TiwitterIcon";
export * from "./LinkedInIcon";
export * from "./GithubIcon";
export * from "./InstagramIcon";
export * from "./ThreadsIcon";
export * from "./ArrowIcon"